## lombok ?????? Enable annotation processing ??
## Postgresql
spring:
  datasource:
    username: admin
    password: admin
    mapper-locations: classpath:/mapper/**/*.xml
    jdbc-url: jdbc:postgresql://localhost:5432/dvdrental
    driver: org.postgresql.Driver

# mybatis ?? ??
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml

# vue ? ?? ?? ?? ?? ?? 8081? ??
server:
  port: 8081

# jpa ????
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      #show_sql: true
      format_sql: true
      default_batch_fetch_size : 100
  generate-ddl: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace